//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XpertGroup.Web.CubeSumService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CubeSumService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCubeSum", ReplyAction="http://tempuri.org/IService/GetCubeSumResponse")]
        string GetCubeSum(string[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCubeSum", ReplyAction="http://tempuri.org/IService/GetCubeSumResponse")]
        System.Threading.Tasks.Task<string> GetCubeSumAsync(string[] value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : XpertGroup.Web.CubeSumService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<XpertGroup.Web.CubeSumService.IService>, XpertGroup.Web.CubeSumService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCubeSum(string[] value) {
            return base.Channel.GetCubeSum(value);
        }
        
        public System.Threading.Tasks.Task<string> GetCubeSumAsync(string[] value) {
            return base.Channel.GetCubeSumAsync(value);
        }
    }
}
